spring.datasource.url=jdbc:postgresql://localhost:5432/researchCenter
spring.datasource.username=postgres
spring.datasource.password=passer
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=true
spring.jpa.show-sql=true
# Swagger Configuration
springdoc.swagger-ui.path=/api-docs
springdoc.api-docs.path=/v3/api-docs
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=9000

# OAuth2 Configuration
# Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email